name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        node-version: ${{ matrix.node-version }}
        

    - name: Build
      run: |
        npm install
        npx webpack
